version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
    commands:
      - npm i -g yarn@1.16.0
      - yarn
      - echo "install commands"

  pre_build:
    commands:
      - sudo docker pull docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.3
      - sudo docker pull grokzen/redis-cluster:4.0.9
      - echo "pre_build commands"

  build:
    commands:
      - echo "build commands"

  post_build:
    commands:
      - echo "post-build commands"